[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1000

[invariant]
runs = 1
depth = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "ds-test/=lib/erc20-helpers/lib/forge-std/lib/ds-test/src/",
    "erc20-helpers/=lib/erc20-helpers/src/",
    "forge-std/=lib/forge-std/src/"
]
